### PR TITLE
style (css): Updated NavigationDrawerItem style to add transitions + selected color

### PR DESCRIPTION
**Pull request by m-doescode**
#### Description of Change

This commit adds transitions and a selected foreground color to the NavigationDrawerItem class (as seen in the settings menu).

#### Linked Issue(s)
* #80

#### Checklist

- [X] PR description included
- [X] PR title follows semantic [commit guidelines](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)
- [x] PR release notes describe the change, and are capitalized, punctuated, and past tense.

- [X] Updated NavigationMenuDrawer
- [ ] Updated text in about page

#### Release Notes
* Changed visuals for NavigationDrawerItem in Settings page.

### CODE REVIEW

**Comment by m-doescode** [comment]
Please do not accept this pull request yet! I have forgotten to add dark theme support.

Thanks, Majd

**Comment by m-doescode** [comment]
I have noticed that the text in the about page shows a pointer cursor instead of a text cursor. Is this intended behavior? If not, should I add this to the pull request? (and rename it, of course)

**Comment by snaildos** [comment]
> I have noticed that the text in the about page shows a pointer cursor instead of a text cursor. Is this intended behavior? If not, should I add this to the pull request? (and rename it, of course)

Hello M,
Regarding your PR thank you for your contribution.
No, this is not expected behaviour. 
It would be great if it got added to the PR.
Kind regards,
SnailDOS

**Comment by snaildos** [comment]
Also, currently you are merging into the "main" branch, could you please set that to "fifo_rewrite"? 
Kind regards,
SnailDOS

**Comment by m-doescode** [comment]
> Also, currently you are merging into the "main" branch, could you please set that to "fifo_rewrite"? Kind regards, SnailDOS

Would it also be necessary to rebase my forked branch? If so, I'm kind of having trouble with that. If you could help, that would be awesome!

Thanks, M

**Comment by m-doescode** [comment]
I'm sorry, I think I've screwed up this pull request, and right now I'm sort of panicking.

What should I do?

**Comment by snaildos** [comment]
Hello M, Yeah, this won't work, just set the pull request back to main, I'll need to work out something when I merge fifo_rewrite into main. It's all good.
Kind regards,
SnailDOS

**Comment by m-doescode** [comment]
> Hello M, Yeah, this won't work, just set the pull request back to main, I'll need to work out something when I merge fifo_rewrite into main. It's all good. Kind regards, SnailDOS

Ok, all done. Really sorry to bother you, I'm bad at git.

Thanks, M

**Review by snaildos — APPROVED** [review]

**Comment by snaildos** [comment]
Hello M,
This PR looks like it is ready to be merged.
Thank you for supporting this project!
Kind regards,
SnailDOS

**Pull request merged**
